#.buildkite/pipeline.yml
# 该文件定义了在 Buildkite Agent 上执行的完整部署流程。

# 定义流水线级别的环境变量，这些变量对所有步骤都可用。
env:
  # 您的 GitHub 用户名，用于 Docker 登录。建议在此处设置或在集群/Agent级别设置。
  GITHUB_USERNAME: "guanqi-lab"

steps:
  # 步骤一：认证并拉取 Docker 镜像
  - label: ":docker: Pull Image"
    key: "pull-image"
    command: "scripts/pull_and_set_metadata.sh"
    # 定义此步骤运行在哪些 Agent 上，例如具有 docker 能力的 Agent
    agents:
      queue: "deployment-agents"

  # 等待步骤：确保上一步成功完成后再继续
  - wait

  # 步骤二：执行部署
  - label: ":rocket: Deploy Application"
    key: "deployment-step"
    command: "scripts/deploy.sh"
    # 定义依赖关系，确保此步骤在 "pull-image" 成功后才运行
    depends_on: "pull-image"
    agents:
      queue: "deployment-agents"
    # 使用插件机制附加一个 post-command 钩子，用于发送通知
    # 注意：这里的插件地址是示例，您需要指向一个包含钩子脚本的私有插件仓库或使用其他钩子机制
    plugins:
      - git@github.com:your-org/buildkite-hooks.git#main:
          hooks:
            post-command: "scripts/notify_lark.sh"