#.buildkite/pipeline.yml
# 通用 Buildkite Pipeline 配置 - 基于分支自动判断环境

# =================== 环境配置 (可根据项目需求修改) ===================
env:
  # Agent 队列配置
  PROD_AGENT_QUEUE: "prod_server"      # 生产环境 Agent 队列名称
  TEST_AGENT_QUEUE: "test_server"      # 测试环境 Agent 队列名称
  
  # 配置前缀设置 (用于配置管理)
  PROD_CONFIG_PREFIX: "PROD_"   # 生产环境配置前缀
  TEST_CONFIG_PREFIX: "TEST_"   # 测试环境配置前缀

steps:
  # Step 0: 初始化权限设置
  - label: "Initialize Scripts Permissions"
    key: "init-permissions"
    command: |
      echo "--- 设置脚本执行权限"
      find scripts/ -name "*.sh" -type f -exec chmod +x {} \;
      echo "✅ 脚本权限设置完成"
    agents:
      queue: "${AGENT_QUEUE}"

  # Step 1: 拉取镜像 (统一逻辑，使用环境变量指定队列)
  - label: "Pull Image"
    key: "pull-image"
    command: "scripts/common/image-puller.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    depends_on: "init-permissions"

  # 等待镜像拉取完成
  - wait

  # Step 2: 应用部署 (统一逻辑，使用环境变量指定队列)
  - label: "Deploy Application"
    key: "deploy"
    command: "scripts/common/deploy-orchestrator.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    depends_on:
      - "pull-image"

  # 等待部署步骤完成（无论成功失败）
  - wait: ~
    continue_on_failure: true

  # Step 3: 发送通知（无论部署成功失败都会执行）
  - label: "Send Notification"
    key: "notify-result"
    command: "scripts/common/notifier.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    soft_fail: true