#.buildkite/pipeline.yml
# 通用 Buildkite Pipeline 配置 - 配置驱动版本

# =================== 环境配置 ===================
# 配置现在通过 GitHub Actions 从 config.yml 传递
# 可用的环境变量：
# - AGENT_QUEUE: Agent 队列名称
# - CONFIG_PREFIX: 配置前缀
# - DEPLOY_ENVIRONMENT: 部署环境
# - CONFIG_KEYS: 配置键列表
# - CONFIG_OUTPUT_FILE: 配置输出文件路径
# - DEPLOY_SCRIPT: 自定义部署脚本路径
# - DEPLOY_TIMEOUT: 部署超时时间

steps:
  # Step 0: 环境初始化
  - label: "Environment Initialization"
    key: "init"
    command: "scripts/buildkite/common/init.sh"
    agents:
      queue: "${AGENT_QUEUE}"

  # Step 1: 拉取镜像 (统一逻辑，使用环境变量指定队列)
  - label: "Pull Image"
    key: "pull-image"
    command: "scripts/buildkite/common/image-puller.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    depends_on: "init"

  # 等待镜像拉取完成
  - wait

  # Step 2: 应用部署 (统一逻辑，使用环境变量指定队列)
  - label: "Deploy Application"
    key: "deploy"
    command: "scripts/buildkite/common/deploy-orchestrator.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    depends_on:
      - "pull-image"

  # 等待部署步骤完成（无论成功失败）
  - wait: ~
    continue_on_failure: true

  # Step 3: 发送通知（无论部署成功失败都会执行）
  - label: "Send Notification"
    key: "notify-result"
    command: "scripts/buildkite/common/notifier.sh"
    agents:
      queue: "${AGENT_QUEUE}"
    soft_fail: true